---
- name: Copy containerd modules config file
  become: yes 
  copy:
    src: files/containerd.conf
    dest: /etc/modules-load.d/containerd.conf
    
- name: Copy k8s CRI conf file
  become: yes
  copy:
    src: files/99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    
- name: Load system settings from conf file
  become: yes
  shell: sysctl --system
  
- name: Add docker CE repository
  become: yes
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

# No able to make that work
# The provided base 
# - name: Add docker CE repository
#   become: yes
#   yum_repository:
#     name: docker-ce
#     description: docker CE repository
#     baseurl: "https://download.docker.com/linux/centos"
  
- name: Install containerd
  become: yes
  yum:
    name: containerd
    state: latest
    
- name: Create containerd directory
  become: yes
  file:
    path: /etc/containerd
    state: directory
    
- name: Create containerd default configuration
  become: yes
  shell: containerd config default | tee /etc/containerd/config.toml
  
# - name: Update containerd configuration

- name: Restart containerd
  become: yes
  service:
    name: containerd
    state: restarted
    enabled: true
