---
- name: Add kubelet paramters through /etc/sysconfig/kubelet
  become: true
  template:
    src: kubelet.j2
    dest: /etc/sysconfig/kubelet
    
- name: Restart kubelet
  service:
    name: kubelet
    state: restarted

# Add kc alias


